### ISSUE TITLE
[BE] DB설계 

### ISSUE THREAD

**Issue by bong6981** [ghis22130/sidedish#1]
- API를 보고 간략한 DB 설계를 한다

**Comment by kihyuk-sung** [comment]
![OnlineBanchanService_Schema](https://user-images.githubusercontent.com/75236235/115204830-e017eb00-a133-11eb-8539-f145706788b0.PNG)

**Comment by bong6981** [comment]
![image](https://user-images.githubusercontent.com/73228803/115813537-4bacd180-a42e-11eb-87e8-05957909493e.png)
